name: Code Scanning
on: [push]
jobs:
  golangci-lint-code-scanning:
    name: Code Scanning with errorformat / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - run: go install ./cmd/errorformat/
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - run: golangci-lint run --out-format=line-number | errorformat -name=golangci-lint -w=sarif > results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
